### ISSUE TITLE
Proposal: Notifications

### ISSUE THREAD

**Issue by dukesteen** [viceroypenguin/Immediate.Handlers#26]
Proposal on adding MediatR like "notifications" aka events aka queries without return types that can fan out to multiple handlers. This issue serves as my brainstorming ground. Feel free to suggest changes.

Concrete example:
**SomeNotification.cs**
```cs
[Notification]
internal sealed record SomeNotification(string NotificationParameter);

[NotificationHandler]
internal class SomeNotificationHandler : INotificationHandler<SomeNotification> // <-- This can also be sg'ed perhaps?
{
    public async ValueTask HandleAsync(SomeNotification notification, CancellationToken token)
    {
        // Your code to do whatever with the notification
    {
}
```
Generated code:
Code for the notification handler would look similar to the existing query handlers

**Publisher.g.cs**
```cs
internal interface IPublisher
{
    public async ValueTask Publish(SomeNotification notification)
    // ... overloads for other notifications
}

internal sealed class NotificationPublisher(IServiceCollection services) : IPublisher
{
    public async ValueTask Publish(SomeNotification notification, CancellationToken token)
    {
        var notificationHandlers = services.GetRequiredService<IEnumerable<INotificationHandler<SomeNotification>>>()

        foreach(var notificationHandler in notificationHandlers)
        {
             notificationHandler.HandleAsync(notification, token)
        }
    }
}
```

Another option would be to resolve every notificationhandler seperately in the `Publish()` method so you can instantly see all the places where a notification is being handled.
Feedback/suggestions appreciated

**Comment by Sossenbinder** [comment]
I really like the `IPublisher` approach, that's very convenient.

Would something speak against sticking to our idea of removing the IServiceCollection middle man with your approach? It's looking a bit like MediatR now, since the publisher would now resolve the handlers on the fly.

I think we could cut that out and allow the consumer of the library to declare N `[NotificationHandler]`, which would all be registered to MSDI. Then a `NotificationPublisher<T>` could be registered, which would receive all handlers through constructor injection, like:

```
internal sealed class NotificationPublisher<T>(IEnumerable<INotificationHandler<T>> handlers) : IPublisher<T>
{
    public async ValueTask Publish(SomeNotification notification, CancellationToken token)
    {
        foreach(var notificationHandler in handlers)
        {
             notificationHandler.HandleAsync(notification, token)
        }
    }
}
```

The code publishing the notifications could then simply inject the respective publisher

```
internal sealed class Processor(IPublisher<T> publisher)
{
    public async Task DoSomething()
    {
        await publisher.Publish(new(), CancellationToken.None);
    }
}
```

That would mean we have not one `IPublisher` but a `IPublisher<T>` per `T` though

**Comment by viceroypenguin** [comment]
**Immediate.Handlers.Shared.NotificationAttribute.cs**
```cs
[AttributeUsage(AttributeTargets.Assembly)]
public sealed class NotificationAttribute<TNotification>(params Type[] types) : Attribute
{
  public Type[] Types { get; } = types;
}
```

**Immediate.Handlers.Shared.Notifier.cs**
```cs
public interface Notifier<TNotification>
{
  ValueTask Notify(TNotification notification, CancellationToken token);
}
```

** Consumer Code **
```cs
[assembly: Notification<SomeNotification>(
  typeof(ConcreteHandler),
  typeof(GenericHandler<SomeNotification>)
)]
```

** Generated Code **
```cs
public class NotificationPublisher(
  ConcreteHandler handler1,
  GenericHandler<SomeNotification> handler2
)
  : IPublisher<SomeNotification>
{
  public async ValueTask Publish(
    SomeNotification notification,
    CancellationToken token
  )
  {
    await Task.WhenAll(
      await handler1.Notify(notification, token),
      await handler2.Notify(notification, token),
      token
    );
}
```

**Comment by Head0nF1re** [comment]
```csharp
await Task.WhenAll(
  handler1.Notify(notification, token),
  handler2.Notify(notification, token),
  token
);
```

This seems like a better fit as it will aggregate all exceptions. The only downside is if you wish to opt for a different way of doing things, like run and await each `Task` sequentially. MediatR allows [custom notification publishers](https://github.com/jbogard/MediatR/wiki#notifications), in case the user wishes to override the default.

Maybe having a `NotificationPublisherAttribute`:

```csharp
[AttributeUsage(AttributeTargets.Assembly | AttributeTargets.Class)]
public sealed class NotificationPublisherAttribute<TNotification>(Type type) : Attribute
{
  public Type Types { get; } = types;
}

[assembly: NotificationPublisher(typeof(MyCustomNotificationPublisher))]
[assembly: Notification<SomeNotification>(
  typeof(ConcreteHandler),
  typeof(GenericHandler<SomeNotification>)
)]
```
`Task.WhenAll` seems like a good default, but what are your thoughts on allowing different stratagies?

**Comment by viceroypenguin** [comment]
The publisher is trivially implemented as:
```cs
public class Publisher<TNotification>(IEnumerable<IHandler<TNotification, ValueTuple>> handlers)
{
  public async ValueTask Publish(TNotification notification, CancellationToken token)
  {
    await Task.WhenAll(
      handlers.Select(async h => await h.HandleAsync(notification, token)));
  }
}
```

and registered via:
```cs
services.AddScoped(typeof(Publisher<>));
```

This relies on existing IH infrastructure, and does not need any further changes from immediate.handlers. Please reopen if you disagree.

**Comment by vinaghost** [comment]
@viceroypenguin hi, your implementation works, but it doesn't support multiple notifications in same handler

```cs
[Handler]
public static partial class ClaimQuestTaskTrigger
{
       private static async ValueTask HandleAsync(
           QuestUpdated notification,
           CancellationToken cancellationToken)
       {
               await Trigger(notification.AccountId, notification.VillageId);
       }
      
       private static async ValueTask HandleAsync(
           VillageSettingUpdated notification,
           CancellationToken cancellationToken)
       {
               await Trigger(notification.AccountId, notification.VillageId);
       }
      
        private static async ValueTask Trigger(AccountId accountId, VillageId villageId) {
              await ValueTask.CompletedTask;
        }
}
```
The error is 
```
error IHR0010: Method 'HandleAsync' must not conflict with another static handler method
```

Any workaround for this situation besides making multiple [Handler] class?

**Comment by viceroypenguin** [comment]
@vinaghost  Making multiple `[Handler]` classes is explicitly the only way to do this.

**Comment by vinaghost** [comment]
@viceroypenguin I saw [martinothamar/Mediator](https://github.com/martinothamar/Mediator) allow multiple Handle method in 1 handler class, but that library uses service locator pattern like [MediatR](https://github.com/jbogard/MediatR).
Do you plan to support that? In my case, multiple [Handler] classes for 1 trigger seem too much.

**Comment by viceroypenguin** [comment]
@vinaghost I don't currently have a plan to support that, no. It should be possible, but my personal opinion is that it would break the SRP of the handler. I would move the `Trigger()` method to a `static` class that could be accessed by both handlers. But I would be willing to consider it if you wanted to write the PR to support it.

**Comment by vinaghost** [comment]
> [@vinaghost](https://github.com/vinaghost) I don't currently have a plan to support that, no. It should be possible, but my personal opinion is that it would break the SRP of the handler. I would move the `Trigger()` method to a `static` class that could be accessed by both handlers. But I would be willing to consider it if you wanted to write the PR to support it.

ok thanks. I will take a look at that in my free time
