### ISSUE TITLE
Ability for consumers to use one generic handler, akin to IMediator

### ISSUE THREAD

**Issue by Atulin** [viceroypenguin/Immediate.Handlers#37]
Currently, one of the best things about MediatR is the fact, that I can only ever inject a single dependency into my controller and use that to handle all different commands

```cs
public class StuffController(IMediator mediator)
{
    [HttpGet("foo")]
    public async Task<Ok<int>> GetFoo([FromQuery]FooHandler.Command command)
        => await mediator.Send(command);

    [HttpGet("bar")]
    public async Task<Ok<int>> GetBar([FromQuery]BarHandler.Command command)
        => await mediator.Send(command);

    [HttpGet("baz")]
    public async Task<Ok<int>> GetBaz([FromQuery]BazHandler.Command command)
        => await mediator.Send(command);
}
```

meanwhile, with Immediate.Handlers, it seems like I need a separate handler for everything, more akin to

```cs
public class StuffController(FooHandler.Handler fooHandler, BarHandler.Handler barHandler, BazHandler.Handler bazHandler)
{
    [HttpGet("foo")]
    public async Task<Ok<int>> GetFoo([FromQuery]FooHandler.Command command)
        => await fooHandler.HandleAsync(command);

    [HttpGet("bar")]
    public async Task<Ok<int>> GetBar([FromQuery]BarHandler.Command command)
        => await barHandler.HandleAsync(command);

    [HttpGet("baz")]
    public async Task<Ok<int>> GetBaz([FromQuery]BazHandler.Command command)
        => await bazHandler.HandleAsync(command);
}
```

which makes the whole endeavor not much more appealing than just making a bunch of, essentially, single-use services and injecting them. Not counting behaviors, of course, can't get those easily with injected services.

It would be nice if I was able to just inject an `IHandler` and let it rip.

**Comment by viceroypenguin** [comment]
I'm afraid that goes directly against the goals of this particular library. 

The problem with a central `IHandler` or `IMediator`, as you would like to use, is that it hides the actual dependencies that a controller has. Looking at `StuffController` with `IMediator`, you cannot quickly evaluate which handlers it depends on. 

With the independent handlers, the controller now explicitly and directly has a dependency on whichever handlers it needs - this makes it more clear what the controller depends on.

Two potential recommendations:
1. Separate `GetFoo`, `GetBar`, and `GetBaz` into separate controllers, as in [this example](https://github.com/viceroypenguin/VsaTemplate/tree/master/Web/Features/Features/Handlers), where `GetFeatures`, `CreateFeature`, `UpdateFeature`, and `DeleteFeature` are all independent controllers.
2. Use [Mediator](https://github.com/martinothamar/Mediator) which uses a source generator for a more traditional mediator usage.

**Comment by Atulin** [comment]
Oooh, yeah, a like number 1. Thanks!
